version: '3.8'

services:
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: tris_server
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: ["./server", "8080", "0.0.0.0", "5"]

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: tris_client
    depends_on:
      - server
    stdin_open: true
    tty: true
    command: ["./client", "server", "8080", "20"]
